package med.voll.api.physician;

public enum SpecialtyEnum {
   IMMUNOLOGY,
   ANESTHESIOLOGY,
   DERMATOLOGY,
   NEUROLOGY,
   GYNECOLOGY,
   PATHOLOGY,
   PEDIATRICS,
   OPHTHALMOLOGY,
   PSYCHIATRY,
   UROLOGY,
   ONCOLOGY,
   CARDIOLOGY
}
